### ISSUE TITLE
unable to install system update after it has been downloaded

### ISSUE THREAD

**Issue by Fuseteam** [ubports/system-settings#193] opened 2019-12-10 16:04 UTC
apologies for the vague title, i can't seem to word it well. This is and edge case where and update is downloaded but not installed. if in the mean time a new update arrives before the downloaded one is installed, the system appears unable to either install the update or redownload the newer version.

the behavior is that it keeps saying the update is downloaded even when one attempts to "restart and install".

**Comment by Danfro** [comment] 2020-01-05 07:29
I had this a few times as well on my E5. I "think" this happenes when the screen goes blank/is locked and the app gets suspended while downloading. But this is more like a guess. I could not confirm it yet.

I found some attempts to solve this:

1. clear cache of system settings e.g. with UT Tweak Tool, retry to install
2. reboot phone, retry to install
3. wait for another update to come out, skip the stuck one

Suggestion for the title: "unable to install system update after it has been downloaded"

**Comment by Danfro** [comment] 2020-01-05 07:35
The app being suspended will likely result in a cutoff of the network connection. So #98 is likely giving us the reason why this won't work. I am not sure if they are duplicates.

Too related/duplicate of #96

**Comment by Fuseteam** [comment] 2020-01-08 20:32
Uh actually i may not been concise enough but it happens when you down the update but forget to install before the next update comes out
clear cache does not resolve it either
switching channel waiting untill the download finishes and switching back appears to resolved it

**Comment by UniversalSuperBox** [comment] 2020-06-25 20:13
One important case where this occurs is:

## The update (or a newer update) was installed, but settings doesn't know that

System-settings has no idea if a system update is applied or not. Therefore, it [checks if the current build number and the build number of the waiting update are the same](https://github.com/ubports/system-settings/blob/00500fee6bef3d48880de04e132420840c474c79/plugins/system-update/image/imagemanager_impl.cpp#L176-L181). If they are, the update is marked as completed. If they aren't, the update remains "Downloaded". Even if you are on a newer version than the one that is "Downloaded". So if you have version 5 and version 3 was waiting to be installed the last time that system-settings was opened, it will still show update 3 as waiting.

In this case, **the update files are not on disk any more**. They were deleted by an installation of the image upgrade.

The most common way this issue will occur is when you download an update, then use the installer to install a different image.

This issue is purely cosmetic. If a new system update is released and found, that update will be shown instead of the fake "Downloaded" one. Therefore, #240 helps it immensely.

## Other cases?

I've just downloaded the update for today on my FP2, after a new update is released I'll check it again to see if there is a problem with new updates being released when an update is already downloaded. I suspect this will be fixed by re-doing the check for updates (and therefore #240 will fix it in most cases).

**Comment by UniversalSuperBox** [comment] 2020-06-26 14:11
I was able to install the update on my FP2 today, when there was clearly a new update available. However, once the device rebooted after installing, I ran into the first case above.

**Comment by UniversalSuperBox** [comment] 2021-04-15 17:28
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/193

**Closed as completed by UniversalSuperBox** 2021-04-15 17:28 UTC
