### ISSUE TITLE
VPN setup dialog not showing file/folder names when dark theme active

### ISSUE THREAD

**Issue by mr-growl** [ubports/system-settings#244] opened 2020-04-27 11:03 UTC
- Device: Nexus 7 2013 wifi 16GB (flo)
- Channel: RC
- Build: 2020-W17

### Steps to reproduce
1. Turn on the "Suru Dark" theme using the UT Tweak tool
2. open "System Settings"
3. click on "VPN"
4. Add a manual config
5. click on the new config
6. click "Change" on the popup that asks if you want to remove or change the config
7.Click on the dropdown below "Client certificate"
8. Click "Choose Certificate..."

### Expected behavior
In the file browser that appears I can read the names of files and folders

### Actual behavior
The icons for files and folders are visible but the names are not

If I switch the theme back to the default I can see the names.

**Comment by UniversalSuperBox** [comment] 2020-07-24 19:44
Hi @mr-growl, I've transferred this issue to the system-settings repository where it can be more easily found by people working on this component.

I can confirm this issue. It appears the VPN settings dialog implements its own file manager which doesn't use the theme colors:

![Ubuntu Touch VPN settings dialog embedded file manager](https://user-images.githubusercontent.com/21966173/88429357-16e6ed80-cdbc-11ea-962d-accf0bdd84f2.png)

I suspect the best fix to this is removing the embedded file manager and firing a ContentHub request, but I'll leave it up to the implementer.

**Comment by UniversalSuperBox** [comment] 2020-11-25 22:48
This was a duplicate of https://github.com/ubports/settings-components/issues/15, which is now resolved.

**Closed as completed by UniversalSuperBox** 2020-11-25 22:48 UTC
