### ISSUE TITLE
"Back" button will not show in About this device -> storage

### ISSUE THREAD

**Issue by konradybcio** [ubports/system-settings#176] opened 2019-09-09 20:05 UTC
This makes the user need to close the Settings app and reopen it each time they want to leave this section, as seen in the screenshot below that cute little arrow is not present in the top left corner.

![screenshot](https://user-images.githubusercontent.com/32096130/64562685-c904fa80-d34d-11e9-9ddc-e0ca995d8908.png)

**Comment by Danfro** [comment] 2020-01-05 07:31
This a duplicate of #157 .

**Comment by UniversalSuperBox** [comment] 2021-04-15 17:27
Moved to https://gitlab.com/ubports/core/lomiri-system-settings/-/issues/176

**Closed as completed by UniversalSuperBox** 2021-04-15 17:27 UTC
