### ISSUE TITLE
Dash background becomes black when enabling Dash background

### ISSUE THREAD

**Issue by kugiigi** [ubports/system-settings#36] opened 2018-01-07 09:48 UTC
Steps to replicate:
1. Do a fresh install of Ubuntu Touch.
2. Go to the settings app and enable **Dash Background** under **Background** section

Expected:
The dash background is set to the default background image.

Actual:
The dash background becomes black.

Other observations:
This can be fixed by changing the background image so it seems that this only happens when you've never changed the default background image yet.

Device:
Nexus 7 15.04/rc
Nexus 5 16.04/devel

**Comment by cibersheep** [comment] 2018-08-14 19:10
Confirm on Nexus 5 2018-w32
On m10 HD 15.04

**Comment by UniversalSuperBox** [comment] 2020-08-31 21:24
I believe this is a duplicate of https://github.com/ubports/ubuntu-touch/issues/856, and neither is relevant any more. The Dash has been removed from Lomiri.

**Closed as completed by UniversalSuperBox** 2020-08-31 21:24 UTC
